# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

ignored = ["code.cloudfoundry.org/garden-shed*"]

[[constraint]]
  branch = "master"
  name = "code.cloudfoundry.org/archiver"

[[constraint]]
  branch = "master"
  name = "code.cloudfoundry.org/clock"

[[constraint]]
  branch = "master"
  name = "code.cloudfoundry.org/commandrunner"

[[constraint]]
  branch = "master"
  name = "code.cloudfoundry.org/debugserver"

[[constraint]]
  branch = "master"
  name = "code.cloudfoundry.org/garden"

[[constraint]]
  name = "code.cloudfoundry.org/grootfs"
  version = "0.30.0"

[[constraint]]
  branch = "master"
  name = "code.cloudfoundry.org/idmapper"

[[constraint]]
  branch = "master"
  name = "code.cloudfoundry.org/lager"

[[constraint]]
  branch = "master"
  name = "code.cloudfoundry.org/localip"

[[constraint]]
  name = "github.com/burntsushi/toml"
  version = "0.3.0"

[[constraint]]
  name = "github.com/cloudfoundry/dropsonde"
  version = "1.0.0"

[[constraint]]
  name = "github.com/cloudfoundry/gosigar"
  version = "1.1.0"

[[constraint]]
  name = "github.com/containerd/containerd"
  version = "1.1.0"

# TODO: We are using the revision below because moby's latest tag is form last year
# for some reason. The revision references the project state before they bumped to
# golang 1.10. This was causing build failures for guardian on golang 1.9.6.
# Maybe revise after we bump to go 1.10
[[constraint]]
  revision = "05346355dbd4300a21bfd64cda93ea6c5aef0cf0"
  name = "github.com/docker/docker"

[[constraint]]
  name = "github.com/eapache/go-resiliency"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/go-multierror"

[[constraint]]
  name = "github.com/jessevdk/go-flags"
  version = "1.4.0"

[[constraint]]
  branch = "master"
  name = "github.com/kardianos/osext"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/copystructure"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/go-ps"

[[constraint]]
  branch = "master"
  name = "github.com/nu7hatch/gouuid"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "1.5.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.4.0"

[[constraint]]
  name = "github.com/opencontainers/go-digest"
  version = "1.0.0-rc1"

[[constraint]]
  name = "github.com/opencontainers/image-spec"
  version = "1.0.1"

[[constraint]]
  name = "github.com/opencontainers/runc"
  revision = "ec9bf5058614525576e60e210a4e645bbd4d8335"

[[constraint]]
  name = "github.com/opencontainers/runtime-spec"
  version = "1.0.1"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.5"

[[constraint]]
  name = "github.com/st3v/glager"
  version = "0.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/tedsuo/ifrit"

[[constraint]]
  branch = "master"
  name = "github.com/tscolari/lagregator"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[[constraint]]
  name = "github.com/vishvananda/netlink"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/vishvananda/netns"

[[constraint]]
  branch = "master"
  name = "golang.org/x/sys"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.1"

[prune]
  go-tests = true
  unused-packages = true
