#!/usr/bin/env bash
set -e

if [ ! -z "$TAG" ]; then
  tag="--tag $TAG"
fi

build_yml=$1
shift

if [ -z "$GARDEN_REMOTE_ATC_URL" ]; then
  fly -t lite login -c http://192.168.100.4:8080
  fly -t lite e -x -p -i guardian=. -c "$build_yml" "$@"
else
# TODO look at these paths
  fly --target "$GARDEN_REMOTE_ATC_URL" e $tag -p -i guardian=$GOPATH/src/code.cloudfoundry.org/guardian -i grootfs=$GOPATH/src/code.cloudfoundry.org/grootfs -c "$build_yml" "$@"
fi
