#!/usr/bin/env bash
set -e

if [ ! -z "$TAG" ]; then
  tag="--tag $TAG"
fi

build_yml=$1
shift

fly --target "$GARDEN_REMOTE_ATC_URL" e $tag -p -i guardian=$GOPATH/src/code.cloudfoundry.org/guardian -i grootfs=$GOPATH/src/code.cloudfoundry.org/grootfs -c "$build_yml" "$@"
