#!/usr/bin/env bash

set -e

ARGS=$@

DIRS=$(for d in $ARGS; do [ -d "$d" ] && echo "$d"; done)

TASK=ci/guardian.yml
if [ "$TAG" == "xenial" ]; then
  TASK=ci/guardian-xenial.yml
fi
if [ "$GOOS" == "windows" ]; then
  TASK=ci/guardian-windows.yml
fi

if egrep -q gqt <(echo "$ARGS"); then
  ./script/remote-fly $TASK -- $ARGS
elif [ "$(find $DIRS -maxdepth 1 -name '*_linux_test.go')" != "" ]; then
  ./script/remote-fly $TASK -- $ARGS
else
  ginkgo -race -nodes=8 -failOnPending -randomizeAllSpecs -randomizeSuites $ARGS
fi

